const express = require('express');
const cors = require('cors');
const path = require('path');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/ventas', require('./routes/ventas'));
app.use('/api/titulares', require('./routes/titulares'));
app.use('/api/personal', require('./routes/personal'));
app.use('/api/agenda', require('./routes/agenda'));
app.use('/api/documentos', require('./routes/documentos'));
app.use('/api/catalogo', require('./routes/catalogo'));
app.get('/', (req, res) => res.json({ mensaje: 'CRM Solutel API v3 corriendo' }));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Servidor corriendo en http://localhost:${PORT}`));
